# https://hub.docker.com/_/mono/
FROM mono

ARG APT_URL=""

RUN set -eux; \
    # preferred mirror site
    [ -n "$APT_URL" ] && [ "$APT_URL" = 'http://free.nchc.org.tw' ] && [ $(uname -m) = 'x86_64' ] && sed -i -r "/-security/! s,^deb http?://[^/]+/(.*),deb $APT_URL/\1,g" /etc/apt/sources.list; \
    [ -n "$APT_URL" ] && [ "$APT_URL" != 'http://free.nchc.org.tw' ] && sed -i -r "s,^deb http?://[^/]+/(.*),deb $APT_URL/\1,g" /etc/apt/sources.list; \
    # install Node.js v16.x
    # https://github.com/nodesource/distributions/blob/master/README.md#debinstall
    curl -fsSL https://deb.nodesource.com/setup_16.x | bash -; \
    apt-get update; \
    apt-get install -y --no-install-recommends nodejs; \
    # https://classic.yarnpkg.com/en/docs/install
    npm install --location=global yarn; \
    # clean up
    rm -rf /var/lib/apt/lists/* /tmp/*; \
    # smoke test
    msbuild -version && node --version && npm --version && yarn --version;