services:
  loki:
    # https://grafana.com/docs/loki/latest/setup/install/docker/
    image: docker.io/grafana/loki
    restart: always
    volumes:
      - loki_data:/loki
      - ./loki-config.yml:/etc/loki/loki-config.yml:ro
    command:
      # https://grafana.com/docs/loki/latest/configure/
      - -config.file=/etc/loki/loki-config.yml
      # disable anonymous usage reporting
      - -reporting.enabled=false
      # https://grafana.com/docs/loki/latest/operations/storage/table-manager/#retention
      - -table-manager.retention-period=90d
      - -table-manager.retention-deletes-enabled=true
      # mitigating: too many outstanding requests
      # https://github.com/grafana/loki/issues/5123#issuecomment-1167018445
      - -querier.max-outstanding-requests-per-tenant=4096
      - -querier.split-queries-by-interval=15m
      - -query-scheduler.max-outstanding-requests-per-tenant=4096

  promtail:
    # https://grafana.com/docs/loki/latest/clients/promtail/installation/
    image: docker.io/grafana/promtail
    restart: always
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - ./log:/var/log:ro
    environment:
      LOKI_URL: "http://loki:3100/loki/api/v1/push"
    command:
      - -config.expand-env=true
      - -config.file=/etc/promtail/promtail-config.yml

  flog:
    image: docker.io/mingrammer/flog
    command: -t log -f json -d 1s -l -w -o /var/log/generated.log
    volumes:
      - ./log:/var/log:rw

  grafana:
    # https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/
    image: docker.io/grafana/grafana-enterprise
    restart: always
    environment:
      # https://grafana.com/docs/grafana/latest/administration/configuration/
      GF_SERVER_ROOT_URL: "http://www.dev.local"
      # 管理者帳號密碼, 應避免在正式環境中使用預設值
      # GF_SECURITY_ADMIN_USER: 'admin'
      # GF_SECURITY_ADMIN_PASSWORD: 'admin'
      # GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin.pwd
    volumes:
      - grafana_data:/var/lib/grafana
      # https://grafana.com/tutorials/provision-dashboards-and-data-sources/#introduction
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      # 如果要自動匯入 dashboard 的話
      # - ./grafana/dashboards:/var/lib/grafana/dashboards
      # - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
    ports:
      - 127.0.0.1:3000:3000

volumes:
  grafana_data:
  loki_data:
