services:
  registry:
    # https://hub.docker.com/_/registry
    image: docker.io/library/registry:2
    restart: unless-stopped
    volumes:
      - registry_data:/var/lib/registry
    ports:
      - 127.0.0.1:5000:5000

volumes:
  registry_data:
