services:
  registry:
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /run/secrets/registry.auth.htpasswd
    secrets:
      - registry.auth.htpasswd

secrets:
  registry.auth.htpasswd:
    external: true
