services:
  registry:
    # https://hub.docker.com/_/registry
    image: registry:2
    restart: unless-stopped
    volumes:
      - registry_data:/var/lib/registry
    # https://distribution.github.io/distribution/about/deploying/
    # environment:
    #   # 如果要限制存取的話
    #   REGISTRY_AUTH: htpasswd
    #   REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    #   REGISTRY_AUTH_HTPASSWD_PATH: /run/secrets/htpasswd
    #   # 如果要啟用 HTTPS 連線的話
    #   REGISTRY_HTTP_ADDR: 0.0.0.0:443
    #   REGISTRY_HTTP_TLS_CERTIFICATE: /run/secrets/cert.pem
    #   REGISTRY_HTTP_TLS_KEY: /run/secrets/key.pem
    ports:
      - 127.0.0.1:5000:5000
      # 如果要啟用 HTTPS 連線的話
      # - 127.0.0.1:443:443
    # secrets:
    #   - cert.pem
    #   - key.pem

# secrets:
#   htpasswd:
#     file: ../.secrets/htpasswd
#   cert.pem:
#     file: ../.secrets/cert.pem
#   key.pem:
#     file: ../.secrets/key.pem

volumes:
    registry_data: