services:
  registry:
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /run/secrets/htpasswd
    secrets:
      - htpasswd

secrets:
  htpasswd:
    file: ../.secrets/htpasswd
