services:
  registry:
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:8443
      REGISTRY_HTTP_TLS_CERTIFICATE: /run/secrets/cert.pem
      REGISTRY_HTTP_TLS_KEY: /run/secrets/key.pem
    ports:
      - 127.0.0.1:8443:8443
    secrets:
      - cert.pem
      - key.pem

secrets:
  cert.pem:
    file: ../.secrets/cert.pem
  key.pem:
    file: ../.secrets/key.pem
