version: '2'

volumes:
    registry-storage: 

services:
  registry:
    # https://hub.docker.com/_/registry
    image: registry:2
    restart: unless-stopped
    volumes:
      - registry-storage:/var/lib/registry
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.rule=Host(`registry.example.test`)"
      # 如果要啟用 HTTPS 連線的話
      # - "traefik.http.routers.registry.tls=true"
      - "traefik.http.services.registry.loadBalancer.server.port=5000"
      # 如果要限制存取的話
      # - "traefik.http.routers.registry.middlewares=auth-users"
      # echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
      # - "traefik.http.middlewares.auth-users.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/"
  traefik:
    # https://hub.docker.com/_/traefik
    image: traefik
    restart: unless-stopped
    oom_kill_disable: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # 如果有相關配置檔案的話
      # - ./traefik/etc:/etc/traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      # 如果要啟用 HTTPS 連線的話
      # - --entrypoints.websecure.address=:443
      # 如果要自動重導為 HTTPS 的話
      # - --entrypoints.web.http.redirections.entryPoint.to=websecure
      # - --entrypoints.web.http.redirections.entryPoint.scheme=https
      # 如果要使用 file provider 的話
      # - --providers.file.directory=/etc/traefik/dynamic/
      # - --providers.file.watch=true
    ports:
      - '127.0.0.1:80:80'
      - '127.0.0.1:8080:8080'
      # 如果要啟用 HTTPS 連線的話
      # - '127.0.0.1:443:443'
