version: '3'

services:
  registry:
    # https://hub.docker.com/_/registry
    image: registry:2
    restart: always
    ports:
     - '5000:5000'
    # 如果要限制存取的話
    # environment:
      # REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      # REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      # REGISTRY_AUTH: htpasswd
      # REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      # REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ./data:/var/lib/registry
      # 如果要限制存取的話
      # - ./certs:/certs
      # - ./auth:/auth