services:
  chisel-server:
    command:
      - server
      - --reverse
      - --tls-key=/run/secrets/dev.local.key
      - --tls-cert=/run/secrets/dev.local.crt
    environment:
      PORT: 8443
    ports:
      - 127.0.0.1:8443:8443
    secrets:
      - dev.local.crt
      - dev.local.key
  chisel-client:
    secrets:
      - client.crt
      - client.key
secrets:
  client.crt:
    external: true
  client.key:
    external: true
  dev.local.crt:
    external: true
  dev.local.key:
    external: true
