version: '3'
services:
  openldap:
    # https://github.com/osixia/docker-light-baseimage#run-command-line-options
    entrypoint: /container/tool/run --loglevel warning --skip-env-files --skip-startup-files --skip-process-files --