services:
  mysql:
    # https://hub.docker.com/_/mysql
    image: mysql
    user: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root.pwd
      MYSQL_USER: ${MYSQL_USER:-guacamole}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user.pwd
      MYSQL_DATABASE: ${MYSQL_DATABASE:-guacamole}
    volumes:
      - mysql_data:/var/lib/mysql
    secrets:
      - mysql_root.pwd
      - mysql_user.pwd
  guacd:
    # https://hub.docker.com/r/guacamole/guacd
    image: guacamole/guacd
    restart: unless-stopped
  guacamole:
    # https://hub.docker.com/r/guacamole/guacamole
    image: guacamole/guacamole
    restart: unless-stopped
    depends_on:
      - guacd
      - mysql
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE:-guacamole}
      MYSQL_USER: ${MYSQL_USER:-guacamole}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user.pwd
    ports:
      - 127.0.0.1:8080:8080
    secrets:
      - mysql_user.pwd

secrets:
  mysql_root.pwd:
    file: ../.secrets/mysql_root.pwd
  mysql_user.pwd:
    file: ../.secrets/mysql_user.pwd

volumes:
  mysql_data:
