services:
  prometheus:
    # https://github.com/prometheus/prometheus
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus:ro
    command:
      # https://github.com/prometheus/prometheus/blob/main/Dockerfile
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      # https://prometheus.io/docs/prometheus/latest/storage/
      - '--storage.tsdb.retention.time=15d'
      # https://prometheus.io/docs/prometheus/latest/management_api/
      - '--web.enable-lifecycle'
    # 如果需要自訂主機名稱對應IP的話
    # extra_hosts:
    #   - "somehost:127.0.0.2"
    ports:
      - 127.0.0.1:9090:9090
  alertmanager:
    # https://github.com/prometheus/alertmanager
    image: prom/alertmanager
    restart: unless-stopped
    volumes:
      - alertmanager_data:/alertmanager
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - 127.0.0.1:9093:9093
  line-notify-gateway:
    # https://github.com/blakey22/line-notify-gateway
    image: blakey22/line-notify-gateway:v0.0.1
    restart: unless-stopped
    environment:
      TOKEN: 'CHANGEME'
      LOCALE: zh_TW
  grafana:
    # https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/
    image: grafana/grafana-enterprise
    restart: unless-stopped
    # environment:
      # https://grafana.com/docs/grafana/latest/administration/configuration/
      # GF_SERVER_ROOT_URL: 'http://monitor.dev.local'
      # 管理者帳號密碼, 應避免在正式環境中使用預設值
      # GF_SECURITY_ADMIN_USER: 'admin'
      # GF_SECURITY_ADMIN_PASSWORD: 'admin'
      # GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin.pwd
    volumes:
      - grafana_data:/var/lib/grafana
      # https://grafana.com/tutorials/provision-dashboards-and-data-sources/#introduction
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      # 如果要自動匯入 dashboard 的話
      # - ./grafana/dashboards:/var/lib/grafana/dashboards
      # - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    ports:
      - 127.0.0.1:3000:3000
  node_exporter:
    # https://github.com/prometheus/node_exporter
    image: prom/node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
  blackbox_exporter:
    # https://github.com/prometheus/blackbox_exporter
    image: prom/blackbox-exporter
    restart: unless-stopped
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml:ro

volumes:
  alertmanager_data:
  prometheus_data:
  grafana_data: