version: '2'

services:
  prometheus:
    # https://github.com/prometheus/prometheus
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus:ro
    command:
      # https://github.com/prometheus/prometheus/blob/main/Dockerfile
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      # https://prometheus.io/docs/prometheus/latest/storage/
      - '--storage.tsdb.retention.time=15d'
      # https://prometheus.io/docs/prometheus/latest/management_api/
      - '--web.enable-lifecycle'
    # 如果需要自訂主機名稱對應IP的話
    # extra_hosts:
    #   - "somehost:127.0.0.2"
  alertmanager:
    # https://github.com/prometheus/alertmanager
    image: prom/alertmanager
    restart: unless-stopped
    volumes:
      - alertmanager-data:/alertmanager
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
  line-notify-gateway:
    # https://github.com/blakey22/line-notify-gateway
    image: blakey22/line-notify-gateway:v0.0.1
    restart: unless-stopped
    environment:
      TOKEN: 'CHANGEME'
      LOCALE: zh_TW
  grafana:
    # https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/
    image: grafana/grafana-enterprise
    restart: unless-stopped
    environment:
      # https://grafana.com/docs/grafana/latest/administration/configuration/
      GF_SERVER_ROOT_URL: 'http://www.dev.local'
      # 管理者帳號密碼, 應避免在正式環境中使用預設值
      # GF_SECURITY_ADMIN_USER: 'admin'
      # GF_SECURITY_ADMIN_PASSWORD: 'admin'
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      # https://grafana.com/tutorials/provision-dashboards-and-data-sources/#introduction
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
    labels:
      - traefik.enable=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.rule=Host(`www.dev.local`)
  cadvisor:
    # https://github.com/google/cadvisor
    image: gcr.io/cadvisor/cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      # - /dev/disk:/dev/disk:ro # Linux only
      # Linux only
      # devices: 
      #   - /dev/kmsg:/dev/kmsg
      # privileged: true
  node-exporter:
    # https://github.com/prometheus/node_exporter
    image: prom/node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
  blackbox-exporter:
    # https://github.com/prometheus/blackbox_exporter
    image: prom/blackbox-exporter
    restart: unless-stopped
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml:ro
  traefik:
    image: traefik
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # 如果有相關配置檔案的話
      # - ./traefik/etc:/etc/traefik
    command:
      # https://doc.traefik.io/traefik/operations/dashboard/#secure-mode
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      # 如果要啟用 HTTPS 連線的話
      # - --entrypoints.websecure.address=:443
      # - --entrypoints.websecure.http.tls=true
      # 如果要自動重導為 HTTPS 的話
      # - --entrypoints.web.http.redirections.entryPoint.to=websecure
      # - --entrypoints.web.http.redirections.entryPoint.scheme=https
      # 如果要使用 file provider 的話
      # - --providers.file.directory=/etc/traefik/dynamic/
      # - --providers.file.watch=true
      # https://doc.traefik.io/traefik/observability/metrics/prometheus/
      - --metrics.prometheus=true
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:8080:8080
      # 如果要啟用 HTTPS 連線的話
      # - 127.0.0.1:443:443

volumes:
  alertmanager-data:
  prometheus-data:
  grafana-data: