services:
  keycloak:
    # https://github.com/keycloak/keycloak/tree/main/quarkus/container
    # 如果要優化容器節省啟動時間的話, 需以建置選項自訂建置映像檔
    # https://www.keycloak.org/server/containers
    image: quay.io/keycloak/keycloak
    restart: unless-stopped
    volumes:
      - keycloak_data:/opt/keycloak/data
      # 如果要匯入與匯出的話
      # - ./import:/opt/keycloak/data/import
      # - ./export:/opt/keycloak/data/export
    environment:
      # https://www.keycloak.org/server/configuration-production#_configure_keycloak_server_with_ipv4_or_ipv6
      JAVA_OPTS_APPEND: -Djava.net.preferIPv4Stack=true
      # https://www.keycloak.org/server/configuration
      # 管理者帳號密碼, 應避免在正式環境中使用預設值
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD:-admin}
      # https://www.keycloak.org/server/all-config
      # 如果前端有使用反向代理的話
      # KC_PROXY_HEADERS: xforwarded
      # 非開發模式要啟用 HTTP 未加密連線的話
      # KC_HTTP_ENABLED: 'true'
      # 如果要啟用健康檢查的話
      KC_HEALTH_ENABLED: "true"
      # https://www.keycloak.org/server/logging
      # KC_LOG_LEVEL: 'info,org.keycloak:debug'
      # https://github.com/keycloak/keycloak/issues/13933
      QUARKUS_HTTP_HTTP2: "false"
    # https://www.keycloak.org/server/configuration#_starting_keycloak
    command: start-dev
    healthcheck:
      test: "{ printf >&3 'HEAD /realms/master/.well-known/openid-configuration HTTP/1.0\r\nHost: localhost\r\nConnection: close\r\n\r\n'; cat <&3; } 3<>/dev/tcp/localhost/8080 | head -1 | grep 200"
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 127.0.0.1:8080:8080

volumes:
  keycloak_data:
