services:
  keycloak:
    environment:
      KC_HTTPS_PORT: "8443"
      KC_HTTPS_CERTIFICATE_KEY_FILE: /run/secrets/dev.local.key
      KC_HTTPS_CERTIFICATE_FILE: /run/secrets/dev.local.key
    ports:
      - 127.0.0.1:8443:8443
    secrets:
      - dev.local.key
      - dev.local.key

secrets:
  dev.local.crt:
    external: true
  dev.local.key:
    external: true
