version: '2'

services:
  keycloak:
    # https://github.com/keycloak/keycloak/tree/main/quarkus/container
    image: quay.io/keycloak/keycloak
    restart: unless-stopped
    environment:
      # https://www.keycloak.org/server/configuration
      # 管理者帳號密碼, 應避免在正式環境中使用預設值
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      # https://www.keycloak.org/server/all-config
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-keycloak}
      KC_DB_USERNAME: ${MYSQL_USER:-keycloak}
      KC_DB_PASSWORD: ${MYSQL_PASSWORD:-keycloak}
      # 如果前端有使用反向代理的話
      KC_PROXY: edge
      # 非開發模式要啟用 HTTP 連線的話
      KC_HTTP_ENABLED: 'true'
      KC_HOSTNAME: 'auth.dev.local'
      # https://www.keycloak.org/server/health
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      # https://www.keycloak.org/server/logging
      # KC_LOG_LEVEL: 'info,org.keycloak:debug'
      # https://www.keycloak.org/server/features
      # KC_FEATURES: scripts
      # 如果要等待連接偵錯用戶端的話
      # DEBUG_SUSPEND: 'y'
      # 如果要偵錯容器內的應用程式的話, 預設為 8787
      # DEBUG_PORT: '*:8787'
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./import:/opt/keycloak/data/import
      - ./export:/opt/keycloak/data/export
    # 正式環境, 請修改 command 為 start --optimized
    # 如果要偵錯容器內的應用程式的話, 請加上 --debug 參數
    # https://www.keycloak.org/server/configuration#_starting_keycloak
    command: start-dev --import-realm
    # ports:
      # 如果要偵錯容器內的應用程式的話
      # - '127.0.0.1:5005:8787'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`auth.dev.local`)"
      # 如果要啟用 HTTPS 連線的話
      # - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.http.services.keycloak.loadbalancer.healthCheck.path=/health/ready"
    depends_on:
      - mysql
  mysql:
    # https://hub.docker.com/_/mysql
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_USER: ${MYSQL_USER:-keycloak}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-keycloak}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-keycloak}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
  # https://doc.traefik.io/traefik/
  traefik:
    # https://hub.docker.com/_/traefik
    image: traefik
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # 如果有相關配置檔案的話
      # - ./traefik/etc:/etc/traefik
    command:
      # https://doc.traefik.io/traefik/operations/dashboard/#secure-mode
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      # 如果要啟用 HTTPS 連線的話
      # - --entrypoints.websecure.address=:443
      # - --entrypoints.websecure.http.tls=true
      # 如果要自動重導為 HTTPS 的話
      # - --entrypoints.web.http.redirections.entryPoint.to=websecure
      # - --entrypoints.web.http.redirections.entryPoint.scheme=https
      # 如果要使用 file provider 的話
      # - --providers.file.directory=/etc/traefik/dynamic/
      # - --providers.file.watch=true
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:8080:8080
      # 如果要啟用 HTTPS 連線的話
      # - 127.0.0.1:443:443

volumes:
    keycloak-data:
    mysql-data: