services:
  nrpe:
    build: .
    image: nrpe:debian
    user: nagios
    restart: unless-stopped
    init: true
    volumes:
      - ./etc/nrpe.cfg:/etc/nagios/nrpe_local.cfg:ro
      - /:/rootfs:ro
    ports:
      - 5666:5666
