---
# https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md
modules:
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ip4"
  tls_connect:
    prober: tcp
    tcp:
      tls: true
  tcp_connect:
    prober: tcp
  icmp:
    timeout: 5s
    prober: icmp
