services:
  alloy:
    command: 
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    ports:
      - 127.0.0.1:12345:12345 # Alloy UI
  otelgen:
    image: ghcr.io/krzko/otelgen