services:
  # https://www.rabbitmq.com/docs/ssl
  rabbitmq:
    volumes:
      - ./conf.d/30-tls.conf:/etc/rabbitmq/conf.d/30-tls.conf:ro
    ports:
      # AMQP over TLS
      - 127.0.0.1:5671:5671
    secrets:
      - dev.local.crt
      - dev.local.key

secrets:
  dev.local.crt:
    external: true
  dev.local.key:
    external: true
