version: '2'

services:
  # https://github.com/j8r/dockerfiles/issues/10
  debian:
    build: .
    image: debian/systemd:11
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  rocky:
    build:
      context: .
      dockerfile: Dockerfile.rocky
    image: rockylinux/systemd:8
    privileged: true
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro