version: '2'
services:
  # https://github.com/j8r/dockerfiles/issues/10
  centos:
    build:
      context: .
      dockerfile: Dockerfile.centos
    image: centos/systemd:8
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  centos7:
    build: 
      context: .
      dockerfile: Dockerfile.centos
      args:
        CENTOS_VERSION: 7
    image: centos/systemd:7
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  debian:
    build: 
      context: .
      args:
        APT_URL: http://free.nchc.org.tw
    image: debian/systemd:10
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  debian9:
    build: 
      context: .
      args:
        APT_URL: http://free.nchc.org.tw
        DEBIAN_VERSION: 9
    image: debian/systemd:9
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  rocky:
    build:
      context: .
      dockerfile: Dockerfile.rocky
    image: rockylinux/systemd:8
    privileged: true
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro