version: '3'
services:
  # https://github.com/j8r/dockerfiles/issues/10
  centos:
    build: ./centos
    image: centos/systemd:7
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  centos8:
    build: 
      context: ./centos
      args:
        VERSION: 8
    image: centos/systemd:8
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  debian:
    build: ./debian
    image: debian/systemd:10
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  debian9:
    build: 
      context: ./debian
      args:
        VERSION: 9
    image: debian/systemd:9
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro