services:
  java:
    build: ./demo
    image: spring-boot:demo
    restart: unless-stopped
    environment:
      LANG: 'C.UTF-8'
      JAVA_TOOL_OPTIONS: '-Djava.net.preferIPv4Stack=true'
    ports:
      - '127.0.0.1:8080:8080'