services:
  java:
    environment:
      SPRING_SSL_BUNDLE_PEM_SERVER_KEYSTORE_CERTIFICATE: /run/secrets/cert.pem
      SPRING_SSL_BUNDLE_PEM_SERVER_KEYSTORE_PRIVATEKEY: /run/secrets/key.pem
      SERVER_PORT: 8443
      SERVER_SSL_BUNDLE: "server"
    ports:
      - "127.0.0.1:8443:8443"
    secrets:
      - cert.pem
      - key.pem

secrets:
  cert.pem:
    file: ../.secrets/cert.pem
  key.pem:
    file: ../.secrets/key.pem
