services:
  java:
    environment:
      SPRING_SSL_BUNDLE_PEM_SERVER_KEYSTORE_CERTIFICATE: /run/secrets/dev.local.crt
      SPRING_SSL_BUNDLE_PEM_SERVER_KEYSTORE_PRIVATEKEY: /run/secrets/dev.local.key
      SERVER_PORT: 8443
      SERVER_SSL_BUNDLE: "server"
    ports:
      - "127.0.0.1:8443:8443"
    secrets:
      - dev.local.crt
      - dev.local.key

secrets:
  dev.local.crt:
    external: true
  dev.local.key:
    external: true
