version: '3'
services:
  java:
    # https://hub.docker.com/r/appsvc/java
    image: appsvc/java:8-jre8_0000000000
    restart: always
    volumes:
      - ./home:/home
  haproxy:
    image: haproxy:2.0
    restart: always
    volumes:
      - ./etc/haproxy:/usr/local/etc/haproxy:ro
    ports:
      - '127.0.0.1:80:80'
      # 如果要啟用 HTTPS 連線的話
      # - '127.0.0.1:443:443'
