version: '3'
services:
  openldap:
    # https://github.com/osixia/docker-openldap
    image: osixia/openldap
    restart: always
    environment:
      # https://www.openldap.org/doc/admin24/slapdconf2.html#olcLogLevel:%20%3Clevel%3E
      # LDAP_LOG_LEVEL: 256
      # https://github.com/osixia/docker-openldap/blob/stable/image/environment/default.startup.yaml
      LDAP_DOMAIN: example.org
      LDAP_ADMIN_PASSWORD: admin
      LDAP_CONFIG_PASSWORD: config
      LDAP_TLS: 'false'
    volumes:
      - ./home/data/ldap:/var/lib/ldap
      - ./home/slapd.d:/etc/ldap/slapd.d
    # 如果要開放透過本機連接埠存取的話
    #  ports:
    #    - '127.0.0.1:389:389'
