services:
  mssql:
    # https://mcr.microsoft.com/product/mssql/server/about
    build: .
    image: mssql
    restart: unless-stopped
    init: true
    environment:
      # https://learn.microsoft.com/sql/linux/sql-server-linux-configure-environment-variables
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD_FILE: /run/secrets/mssql_root.pwd
      MSSQL_DATABASE: ${MSSQL_DATABASE:-}
      MSSQL_USER: ${MSSQL_USER:-}
      MSSQL_PASSWORD_FILE: /run/secrets/mssql_user.pwd
    volumes:
      - mssql_data:/var/opt/mssql
      # 如果需要自訂組態的話
      # - ./mssql.conf:/var/opt/mssql/mssql.conf:ro
    ports:
      - 127.0.0.1:1433:1433
    secrets:
      - mssql_root.pwd
      - mssql_user.pwd

secrets:
  mssql_root.pwd:
    file: ../.secrets/mssql_root.pwd
  mssql_user.pwd:
    file: ../.secrets/mssql_user.pwd

volumes:
  mssql_data:
