version: '2'

services:
  mssql:
    volumes:
      - ./mssql.conf:/var/opt/mssql/mssql.conf
    secrets:
      - cert.pem
      - key.pem

secrets:
  cert.pem:
    file: ./certs/cert.pem
  key.pem:
    file: ./certs/key.pem