version: '2'

services:
  mssql:
    # https://mcr.microsoft.com/product/mssql/server/about
    build: .
    image: mssql
    restart: unless-stopped
    environment:
      # https://learn.microsoft.com/sql/linux/sql-server-linux-configure-environment-variables
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: '${MSSQL_SA_PASSWORD:-P@ssw0rd}'
      MSSQL_DATABASE: ${MSSQL_DATABASE}
      MSSQL_USER: ${MSSQL_USER}
      MSSQL_PASSWORD: '${MSSQL_PASSWORD}'
    volumes:
      - mssql-data:/var/opt/mssql
      # 如果需要自訂組態的話
      # - ./mssql.conf:/var/opt/mssql/mssql.conf:ro
    ports:
     - 127.0.0.1:1433:1433

volumes:
    mssql-data: