services:
  nessus:
    # https://docs.tenable.com/nessus/Content/DeployNessusDocker.htm
    image: tenable/nessus:latest-ubuntu
    restart: always
    ports:
      - 8834:8834
    environment:
      USERNAME: admin
      PASSWORD: admin