services:
  dotnet:
    build: ./demo
    image: dotnet:demo
    restart: always
    environment:
      ASPNETCORE_HTTP_PORTS: 8080
      # https://learn.microsoft.com/aspnet/core/host-and-deploy/proxy-load-balancer?#forward-the-scheme-for-linux-and-non-iis-reverse-proxies
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    ports:
      - "127.0.0.1:8080:8080"
