services:
  dotnet:
    environment:
      ASPNETCORE_HTTPS_PORTS: 8443
      Kestrel__Certificates__Default__Path: /run/secrets/cert.pem
      Kestrel__Certificates__Default__KeyPath: /run/secrets/key.pem
      # 如果憑證需要密碼的話
      # Kestrel__Certificates__Default__Password: 'changeit'
    ports:
      - '127.0.0.1:8443:8443'
    secrets:
      - cert.pem
      - key.pem

secrets:
  cert.pem:
    file: ../.secrets/cert.pem
  key.pem:
    file: ../.secrets/key.pem