services:
  dotnet:
    environment:
      ASPNETCORE_HTTPS_PORTS: 8443
      Kestrel__Certificates__Default__Path: /run/secrets/cert.p12
      Kestrel__Certificates__Default__Password: 'changeit'
    ports:
      - '127.0.0.1:8443:8443'
    secrets:
      - cert.p12

secrets:
  cert.p12:
    file: ./cert.p12