version: '2'
volumes:
  app-home:


services:
  dotnet:
    # https://hub.docker.com/_/microsoft-dotnet-aspnet/
    image: mcr.microsoft.com/dotnet/aspnet:6.0
    restart: unless-stopped
    volumes:
      # 在 Azure App Service 運作時，僅有 '/home' 目錄可以跨容器存取並永續儲存
      - app-home:/home
    environment:
      LANG: 'C.UTF-8'
      # https://learn.microsoft.com/aspnet/core/fundamentals/configuration/#environment-variables
      # Bash 不支援 `:` 做為階層式索引鍵分隔符號, 必須改用 `__`
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: 'true'
      ASPNETCORE_URLS: http://+:80
    # 如果需要自訂啟動腳本的話
    # command: sh -c "cd /home/site/wwwroot && dotnet WebApp.dll"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dotnet.rule=Host(`dev.example.test`)"
      # 如果要啟用 HTTPS 連線的話
      # - "traefik.http.routers.dotnet.tls=true"
      - "traefik.http.services.dotnet.loadbalancer.server.port=80"
  # https://docs.traefik.io/
  traefik:
    # https://hub.docker.com/_/traefik
    image: traefik
    restart: unless-stopped
    oom_kill_disable: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # 如果有相關配置檔案的話
      # - ./traefik/etc:/etc/traefik
    command:
      # https://doc.traefik.io/traefik/operations/dashboard/#secure-mode
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      # 如果要啟用 HTTPS 連線的話
      # - --entrypoints.websecure.address=:443
      # 如果要自動重導為 HTTPS 的話
      # - --entrypoints.web.http.redirections.entryPoint.to=websecure
      # - --entrypoints.web.http.redirections.entryPoint.scheme=https
      # 如果要使用 file provider 的話
      # - --providers.file.directory=/etc/traefik/dynamic/
      # - --providers.file.watch=true
    ports:
      - '127.0.0.1:80:80'
      - '127.0.0.1:8080:8080'
      # 如果要啟用 HTTPS 連線的話
      # - '127.0.0.1:443:443'
