services:
  nginx:
    volumes:
      - ./templates:/etc/nginx/templates:ro
    environment:
      NGINX_HOST: www.dev.local
      NGINX_PORT: 8443
      NGINX_SSL_CERT: /run/secrets/dev.local.crt
      NGINX_SSL_KEY: /run/secrets/dev.local.key
    ports:
      - "127.0.0.1:8443:8443"
    secrets:
      - dev.local.crt
      - dev.local.key

secrets:
  dev.local.crt:
    external: true
  dev.local.key:
    external: true
