services:
  # https://mariadb.com/kb/en/securing-connections-for-client-and-server/#enabling-tls-for-mariadb-server
  mariadb:
    # 如果要強制所有用戶端連線都必須加密的話可加入 --require-secure-transport 選項
    command: mariadbd --ssl-cert=/run/secrets/cert.pem --ssl-key=/run/secrets/key.pem
    secrets:
      - cert.pem
      - key.pem

secrets:
  cert.pem:
    file: ./certs/cert.pem
  key.pem:
    file: ./certs/key.pem