services:
  ldap:
    # https://github.com/osixia/docker-openldap
    image: osixia/openldap
    restart: unless-stopped
    # https://github.com/osixia/docker-openldap/tree/master/image/environment
    environment:
      # https://github.com/osixia/docker-openldap/issues/462
      LDAP_NOFILE: 8192
    volumes:
      - ldap_conf:/etc/ldap/slapd.d
      - ldap_data:/var/lib/ldap
      # https://github.com/osixia/docker-openldap#seed-ldap-database-with-ldif
      - ./import:/container/service/slapd/assets/config/bootstrap/ldif/custom:ro
    command: --copy-service
    ports:
      - 127.0.0.1:10389:389
  ldap-cli:
    # https://github.com/osixia/docker-openldap
    image: osixia/openldap
    volumes:
      - ldap_conf:/etc/ldap/slapd.d
      - ldap_data:/var/lib/ldap
    # https://github.com/osixia/docker-light-baseimage#run-command-line-options
    entrypoint: /container/tool/run --loglevel warning --skip-env-files --skip-startup-files --skip-process-files --

volumes:
  ldap_conf:
  ldap_data: