services:
  ldap:
    environment:
      LDAP_TLS_CA_CRT_PATH: /run/secrets/dev.CA.crt
      LDAP_TLS_CRT_PATH: /run/secrets/dev.local.crt
      LDAP_TLS_KEY_PATH: /run/secrets/dev.local.key
      # # https://github.com/osixia/docker-openldap/issues/105
      LDAP_TLS_VERIFY_CLIENT: try
    ports:
      - 127.0.0.1:10636:636
    secrets:
      - dev.CA.crt
      - dev.local.crt
      - dev.local.key

secrets:
  dev.CA.crt:
    external: true
  dev.local.crt:
    external: true
  dev.local.key:
    external: true
