services:
  ldap:
    environment:
      LDAP_TLS_CRT_FILENAME: cert.pem
      LDAP_TLS_KEY_FILENAME: key.pem
      LDAP_TLS_CA_CRT_FILENAME: ca.pem
      # # https://github.com/osixia/docker-openldap/issues/105
      LDAP_TLS_VERIFY_CLIENT: try
    volumes:
      - ../.secrets:/container/service/slapd/assets/certs:ro
    ports:
      - 127.0.0.1:636:636
