services:
  ldap:
    # https://github.com/osixia/docker-openldap
    image: osixia/openldap
    restart: unless-stopped
    hostname: ldap
    environment: 
      # https://github.com/osixia/docker-openldap/issues/462
      LDAP_NOFILE: 8192
      # https://www.openldap.org/doc/admin24/slapdconf2.html#olcLogLevel:%20%3Clevel%3E
      LDAP_LOG_LEVEL: 16640
      # https://github.com/osixia/docker-openldap/blob/master/image/environment/default.startup.yaml
      LDAP_DOMAIN: example.org
      LDAP_ADMIN_PASSWORD: admin
      LDAP_CONFIG_PASSWORD: config
      LDAP_REPLICATION: 'true'
      LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap','ldap://ldap2']"
    volumes:
      - ldap_conf:/etc/ldap/slapd.d
      - ldap_data:/var/lib/ldap
    ports:
      - 127.0.0.1:389:389
  ldap-cli:
    # https://github.com/osixia/docker-openldap
    image: osixia/openldap
    volumes:
      - ldap_conf:/etc/ldap/slapd.d
      - ldap_data:/var/lib/ldap
    # https://github.com/osixia/docker-light-baseimage#run-command-line-options
    entrypoint: /container/tool/run --loglevel warning --skip-env-files --skip-startup-files --skip-process-files --
  ldap2:
    # https://github.com/osixia/docker-openldap
    image: osixia/openldap
    restart: unless-stopped
    hostname: ldap2
    environment:
      # https://github.com/osixia/docker-openldap/issues/462
      LDAP_NOFILE: 8192
      # https://www.openldap.org/doc/admin24/slapdconf2.html#olcLogLevel:%20%3Clevel%3E
      LDAP_LOG_LEVEL: 16640
      # https://github.com/osixia/docker-openldap/blob/stable/image/environment/default.startup.yaml
      LDAP_DOMAIN: example.org
      LDAP_ADMIN_PASSWORD: admin
      LDAP_CONFIG_PASSWORD: config
      LDAP_REPLICATION: 'true'
      LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap','ldap://ldap2']"
    volumes:
      - ldap2-conf:/etc/ldap/slapd.d
      - ldap2-data:/var/lib/ldap
    ports:
      - 127.0.0.1:10389:389
  ldap2-cli:
    # https://github.com/osixia/docker-openldap
    image: osixia/openldap
    volumes:
      - ldap2-conf:/etc/ldap/slapd.d
      - ldap2-data:/var/lib/ldap
    # https://github.com/osixia/docker-light-baseimage#run-command-line-options
    entrypoint: /container/tool/run --loglevel warning --skip-env-files --skip-startup-files --skip-process-files --

volumes:
  ldap_conf:
  ldap_data: 
  ldap2-conf:
  ldap2-data: 
