services:
  # https://dev.mysql.com/doc/refman/8.0/en/using-encrypted-connections.html
  mysql:
    # 如果要強制所有用戶端連線都必須加密的話可加入 --require-secure-transport 選項
    command: mysqld --ssl-cert=/run/secrets/cert.pem --ssl-key=/run/secrets/key.pem
    secrets:
      - cert.pem
      - key.pem

secrets:
  cert.pem:
    file: ../.secrets/cert.pem
  key.pem:
    file: ../.secrets/key.pem