services:
  # https://dev.mysql.com/doc/refman/8.0/en/using-encrypted-connections.html
  mysql:
    # 如果要強制所有用戶端連線都必須加密的話可加入 --require-secure-transport 選項
    command: mysqld --ssl-cert=/run/secrets/dev.local.crt --ssl-key=/run/secrets/dev.local.key
    secrets:
      - dev.local.crt
      - dev.local.key

secrets:
  dev.local.crt:
    external: true
  dev.local.key:
    external: true
