version: '3'

services:
  db:
    image: 'mariadb:latest'
    restart: always
    environment:
      # 設定空密碼 (不建議用於正式環境)
      # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      # 指定密碼
      # - MYSQL_ROOT_PASSWORD=secret
      # 產生隨機的初始密碼,將顯示在標準輸出(GENERATED ROOT PASSWORD:...)
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    # 當宿主是 Windows 作業系統時,需要以下配置以正確掛載 /var/lib/mysql
    # https://github.com/docker-library/mariadb/issues/38#issuecomment-385845282
    # command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON
    ports:
     - '3306:3306'
    volumes:
      - ./etc/mysql/conf.d:/etc/mysql/mariadb.conf.d:ro
      - ./etc/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./db:/var/lib/mysql
  # 如果要使用 adminer 管理介面的話
  adminer:
    image: adminer
    # environment:
      # https://github.com/vrana/adminer/tree/master/plugins
      # - ADMINER_PLUGINS=tables-filter tinymce
    ports:
      - '8080:8080'
    depends_on:
      - db