version: '2'

volumes:
    mysql-data: 

services:
  mysql:
    # https://hub.docker.com/_/mysql
    image: mysql
    restart: unless-stopped
    environment:
      # 指定初始化資料庫建立的 root 密碼
      MYSQL_ROOT_PASSWORD: 'CHANGEME'
    volumes:
      - mysql-data:/var/lib/mysql
      # 如果需要自訂組態的話
      # - mysql-conf:/etc/mysql/conf.d:ro
      # 如果需要初始化資料庫的話
      # - ./initdb:/docker-entrypoint-initdb.d
    ports:
     - 127.0.0.1:3306:3306
