# https://prometheus.io/docs/alerting/latest/configuration/
global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtp.sendgrid.net:587'
  smtp_from: 'alertmanager@example.org'
  smtp_auth_username: 'apikey'
  smtp_auth_password: 'SENDGRID_API_KEY'

# The root route on which each incoming alert enters.
route:
  # How long to wait before sending a notification again if it has already
  # been sent successfully for an alert. (Usually ~3h or more).
  repeat_interval: 3h

  # A default receiver
  receiver: email

receivers:
  - name: 'email'
    email_configs:
      - to: 'user@example.com'
      # - to: 'user2@example.com'
