services:
  # https://www.postgresql.org/docs/current/ssl-tcp.html
  postgres:
    command: -c ssl=on -c ssl_cert_file=/run/secrets/dev.local.crt -c ssl_key_file=/run/secrets/dev.local.key
    secrets:
      - dev.local.crt
      - dev.local.key

secrets:
  dev.local.crt:
    external: true
  dev.local.key:
    external: true
