---
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
global:
  scrape_interval: 15s  # default: 1m
  scrape_timeout: 5s  # default: 10s
  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #   monitor: 'dev-monitor'

# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
rule_files:
# https://github.com/samber/awesome-prometheus-alerts
# - rules/prometheus.alert.yml
# - rules/container.alert.yml
# - rules/host.alert.yml
# - rules/blackbox.alert.yml
# - rules/windows.alert.yml

# Alerting specifies settings related to the Alertmanager.
alerting:
  alertmanagers:
    # https://prometheus.io/docs/prometheus/latest/configuration/configuration/#alertmanager_config
    - static_configs:
        - targets:
            - alertmanager:9093

# A list of scrape configurations.
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: node
    # https://prometheus.io/docs/prometheus/latest/configuration/configuration/#static_config
    static_configs:
      - targets:
          - node_exporter:9100
  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: blackbox_http
    metrics_path: /probe
    params:
      module: [http_2xx]
    # https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
    static_configs:
      - targets:
          - https://www.example.com
        labels:
          env: dev
          app: demo
      - targets:
          - https://www.google.com
        labels:
          env: prod
          app: demo
  - job_name: blackbox_tls
    metrics_path: /probe
    params:
      module: [tls_connect]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
    static_configs:
      - targets:
          - www.example.com:443
        labels:
          env: dev
          app: demo
      - targets:
          - www.google.com:443
        labels:
          env: prod
          app: demo
  - job_name: blackbox_tcp
    metrics_path: /probe
    params:
      module: [tls_connect]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
    static_configs:
      - targets:
          - www.example.com:80
        labels:
          env: dev
          app: demo
      - targets:
          - www.google.com:80
        labels:
          env: prod
          app: demo
  - job_name: blackbox_icmp
    metrics_path: /probe
    params:
      module: [icmp]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
    static_configs:
      - targets:
          - www.example.com
        labels:
          env: dev
          app: demo
      - targets:
          - www.google.com
        labels:
          env: prod
          app: demo
# SQL Server
# - job_name: 'mssql'
#   scrape_interval: 1m
#   static_configs:
#     - targets:
#       - localhost:9399
