services:
  php:
    volumes:
      - ./httpd-tls.conf:/etc/apache2/sites-enabled/httpd-tls.conf:ro
    ports:
      - 127.0.0.1:8443:8443
    secrets:
      - dev.local.crt
      - dev.local.key

secrets:
  dev.local.crt:
    external: true
  dev.local.key:
    external: true
