version: '3'
services:
  php:
    # https://hub.docker.com/r/appsvc/php
    image: appsvc/php:7.3-apache_20200522.6
    restart: always
    volumes:
      - ./home:/home
    # 如果要開放透過本機連接埠存取的話
    # ports:
      # - '127.0.0.1:80:80'
    # 如果要自訂 PHP 組態設定的話
    # environment:
      # PHP_INI_SCAN_DIR: '/usr/local/etc/php/conf.d:/home/site/ini'
    # 如果要配置額外的主機名稱對應的話
    # extra_hosts:
      # - "localhost:127.0.0.1"
  haproxy:
    # https://hub.docker.com/_/haproxy
    image: haproxy:2.0
    restart: always
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro
    ports:
      - '127.0.0.1:80:80'
      # 如果要啟用 HTTPS 連線的話
      # - '127.0.0.1:443:443'
