version: '3'

services:
  db:
    image: 'mariadb:10.3'
    restart: always
    environment:
      # 設定空密碼 (不建議用於正式環境)
      # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      # 指定密碼
      # - MYSQL_ROOT_PASSWORD=secret
      # 產生隨機的初始密碼,將顯示在標準輸出(GENERATED ROOT PASSWORD:...)
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    # 如果要開放透過本機連接埠存取容器內的資料庫的話
    # ports:
    #  - '3306:3306'
    # 當宿主是 Windows 作業系統時,需要以下配置以正確掛載 /var/lib/mysql
    # https://github.com/docker-library/mariadb/issues/38#issuecomment-385845282
    command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON
    volumes:
      - ./etc/mysql/conf.d:/etc/mysql/mariadb.conf.d:ro
      - ./etc/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./db:/var/lib/mysql
  # # 如果要使用 adminer 管理介面的話
  # adminer:
  #   image: adminer
  #   ports:
  #     - '8080:8080'
  #   depends_on:
  #     - db
  web:
    image: 'nginx:stable'
    restart: always
    # 如果開放本機連接埠發生衝突,請自行調整埠號
    ports:
      - '80:80'
      # 如果要啟用 HTTPS 連線的話
      # - '443:443'
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./web:/var/www/html
      # 如果要啟用 HTTPS 連線的話
      # - ./etc/nginx/cert.pem:/etc/nginx/cert.pem:ro
      # - ./etc/nginx/cert.key:/etc/nginx/cert.key:ro
    depends_on:
      - fpm
  fpm:
    build: ./php/fpm
    image: app:fpm
    user: www-data
    restart: always
    # 如果要啟用 XDebug 遠端偵錯的話
    # environment:
    #   # 如果不是偵錯本機容器時才需要修改
    #   - XDEBUG_CONFIG=remote_host=host.docker.internal
    volumes:
      - ./web:/var/www/html
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./etc/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf:ro
    depends_on:
      - db
    # 如果要配置額外的主機名稱對應的話
    # extra_hosts:
    #   - "localhost:127.0.0.1"
  cli:
    build: ./php/cli
    image: app:cli
    user: www-data
    working_dir: /var/www/html
    volumes:
      - ./web:/var/www/html
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./etc/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf:ro
    depends_on:
      - db