version: '2'
volumes:
  app-home:

services:
  php:
    build: 
      context: .
      args:
        APT_URL: http://free.nchc.org.tw
    image: php:8.0-apache-ext
    restart: unless-stopped
    volumes:
      # 在 Azure App Service 運作時，僅有 '/home' 目錄可以跨容器存取並永續儲存
      # https://docs.microsoft.com/azure/app-service/configure-custom-container#use-persistent-shared-storage
      - app-home:/home
      - ./index.php:/home/site/wwwroot/index.php:ro
      - ./startup.sh:/home/startup.sh:ro
    environment:
      LANG: 'C.UTF-8'
      APACHE_DOCUMENT_ROOT: /home/site/wwwroot
      # 如果要自訂 PHP 組態設定的話
      # PHP_INI_SCAN_DIR: '/usr/local/etc/php/conf.d:/home/site/ini'
    command: bash /home/startup.sh
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`dev.example.test`)"
      # 如果要啟用 HTTPS 連線的話
      # - "traefik.http.routers.php.tls=true"
      - "traefik.http.services.php.loadBalancer.server.port=80"
  # https://doc.traefik.io/traefik/
  traefik:
    # https://hub.docker.com/_/traefik
    image: traefik
    restart: unless-stopped
    oom_kill_disable: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # 如果有相關配置檔案的話
      # - ./traefik/etc:/etc/traefik
    command:
      # https://doc.traefik.io/traefik/operations/dashboard/#secure-mode
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      # 如果要啟用 HTTPS 連線的話
      # - --entrypoints.websecure.address=:443
      # 如果要自動重導為 HTTPS 的話
      # - --entrypoints.web.http.redirections.entryPoint.to=websecure
      # - --entrypoints.web.http.redirections.entryPoint.scheme=https
      # 如果要使用 file provider 的話
      # - --providers.file.directory=/etc/traefik/dynamic/
      # - --providers.file.watch=true
    ports:
      - '127.0.0.1:80:80'
      - '127.0.0.1:8080:8080'
      # 如果要啟用 HTTPS 連線的話
      # - '127.0.0.1:443:443'
