version: '3'

services:
  db:
    image: 'mariadb:latest'
    restart: always
    environment:
      # 設定空密碼 (不建議用於正式環境)
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      # 指定密碼
      # - MYSQL_ROOT_PASSWORD=secret
      # 產生隨機的初始密碼,將顯示在標準輸出(GENERATED ROOT PASSWORD:...)
      # - MYSQL_RANDOM_ROOT_PASSWORD=yes
    # 如果要開放透過本機連接埠存取容器內的資料庫的話
    # ports:
    #  - '3306:3306'
    volumes:
      - ./etc/mysql/conf.d:/etc/mysql/mariadb.conf.d:ro
      - ./etc/mysql/initdb.d:/docker-entrypoint-initdb.d
      - app-db:/var/lib/mysql
    networks:
      - app-network
  # 如果要使用 phpmyadmin 管理介面的話
  # phpmyadmin:
  #   image: 'phpmyadmin/phpmyadmin'
  #   ports:
  #     # 如果不固定開放本機連接埠號的話
  #     - '80'
  #     # 如果要固定開放本機連接埠號的話
  #     # - '32780:80'
  #   depends_on:
  #     - db
  #   networks:
  #     - app-network
  web:
    image: 'nginx'
    restart: always
    # 如果開放本機連接埠發生衝突,請自行調整埠號
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./etc/nginx/ssl:/etc/nginx/ssl:ro
      - ./web:/var/www/html
    depends_on:
      - fpm
    networks:
      - app-network
  fpm:
    build: ./php/fpm
    image: app:fpm
    restart: always
    # 如果要啟用 XDebug 遠端偵錯的話
    # environment:
    #   # 如果 Docker 宿主(docker.for.win.localhost,docker.for.mac.localhost) 
    #   # 不是 192.168.65.1 或不是偵錯本機容器時才需要修改
    #   - XDEBUG_CONFIG=remote_host=192.168.65.1
    volumes:
      - ./web:/var/www/html
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./etc/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf:ro
    depends_on:
      - db
    networks:
      - app-network
    # 如果要配置額外的主機名稱對應的話
    # extra_hosts:
    #   - "localhost:127.0.0.1"
  cli:
    build: ./php/cli
    image: app:cli
    user: www-data
    working_dir: /var/www/html
    volumes:
      - ./web:/var/www/html
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./etc/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf:ro
    depends_on:
      - db
    networks:
      - app-network

volumes:
  app-db:

networks:
  app-network:
    driver: bridge