services:
  # https://redis.io/docs/management/security/encryption/
  redis:
    command: --port 6379 --tls-port 6380 --tls-cert-file /run/secrets/cert.pem --tls-key-file /run/secrets/key.pem --tls-ca-cert-file /run/secrets/ca.pem --tls-auth-clients no
    ports:
      - 127.0.0.1:6380:6380
    secrets:
      - cert.pem
      - key.pem

secrets:
  ca.pem:
    file: ../.secrets/ca.pem
  cert.pem:
    file: ../.secrets/cert.pem
  key.pem:
    file: ../.secrets/key.pem