services:
  # https://redis.io/docs/latest/operate/oss_and_stack/management/security/encryption/
  redis:
    volumes:
      - redis_data:/data
      - ./etc:/usr/local/etc/redis:ro
    command: /usr/local/etc/redis/redis.conf
    healthcheck:
      test: redis-cli -h localhost -p 6380 --tls --insecure ping
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    ports:
      - 127.0.0.1:6380:6380
    secrets:
      - server.crt
      - server.key

secrets:
  server.crt:
    external: true
  server.key:
    external: true
