version: '2'

services:
  # https://redis.io/topics/encryption
  redis:
    volumes:
      - ./tls:/etc/tls:ro
    command: --port 6379 --tls-port 6380 --tls-cert-file /etc/tls/cert.pem --tls-key-file /etc/tls/key.pem --tls-ca-cert-file /etc/tls/ca.pem --tls-auth-clients no
    ports:
      - 127.0.0.1:6380:6380