version: '2'

volumes:
    redis-storage: 

services:
  redis:
    # https://hub.docker.com/_/redis
    image: redis
    restart: unless-stopped
    volumes:
      - redis-storage:/data
      # 如果需要自訂組態的話
      # - ./etc:/usr/local/etc/redis:ro
    # 如果需要自訂組態的話
    # command: /usr/local/etc/redis/redis.conf
    ports:
      - 127.0.0.1:6379:6379
