services:
  ttyd:
    command:
      - ttyd
      - -W
      - --ssl
      - --ssl-cert=/run/secrets/dev.local.crt
      - --ssl-key=/run/secrets/dev.local.key
      - bash
    secrets:
      - dev.local.crt
      - dev.local.key

secrets:
  dev.local.crt:
    external: true
  dev.local.key:
    external: true
